### ISSUE TITLE
Deutschlandfunk Addon fails to install in LibreELEC

### ISSUE THREAD

**Issue by wechsler42** [Heckie75/kodi-addon-deutschlandfunk#1]
Hi Heckie,
thanks for your work towards a DLF addon.
However, trying to install it in LibreELEC 8.x or 9.x fails due to missing lxml library:
` ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named lxml
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.deutschlandfunk/addon.py", line 20, in <module>
                                                from lxml import html
                                            ImportError: No module named lxml
                                            -->End of Python script error report<--
`

LibreELEC is more ore less a read only OS and therefore no apt-get or python pip is available. Would it be possible to include the lxml library into the plugin or perhaps BeautifulSoup might be an alternative though it is already part of LibreELEC.
Thanks in advance for evaluating this suggestion.

**Comment by Heckie75** [comment]
Dear Wechsler,

You are right. Although I don't use Libreelec on myself I have noticed that my addon doesn't work on libreelec when I tried to install it on my brother's raspberry Pi. There isn't the chance to pack the libs together since there seem to be more and more dependencies. I try to Investigate how the libs work that you have suggested.

Best regargs

**Comment by Heckie75** [comment]
Dear Wechsler,

I have changed the code so that it uses BeautifulSoup now. Could you please check if this addon works on LibreElec?

Let me know if there are exceptions in log file.

Best regards,
Martin

**Comment by wechsler42** [comment]
Dear Heckie75,
thanks for getting into this.
I tested the updated plugin on LibreELEC 8.2.4 (official). The good news is, that I can get the plugin to work after some tinkering. However, here are the log file entries:

Case A: Install  plugin.audio.deutschlandfunk.zip the regular way "install from .zip":
`DEBUG: CAddonInstallJob[plugin.audio.deutschlandfunk]: requires xmbc.addon version 17.0.0 which is not available

ERROR: CAddonInstallJob[plugin.audio.deutschlandfunk]: The dependency on xmbc.addon version 17.0.0 could not be satisfied. `

Case B: Move plugin.audio.deutschlandfunk directory  to /storage/.kodi/addons/ and install script.module.beautifulsoup4.zip from [https://mirrors.kodi.tv/addons/krypton/script.module.beautifulsoup4/](url) --> this works

So my preliminary conclusions are:
- perhaps something needs to be changed in the xbmc.addon requirement, unfortunately I do not know what to change
- script.module.beautifulsoup4.zip should be an automatically installed dependency

Perhaps you find again some time to work on the addon? I would test it again. 
Thanks in advance,
Wechsler42

**Comment by Heckie75** [comment]
Dear Wechsler42,

I have updated the zip file and removed unrequired dependencies in addon.xml. Now I am able to install addon from zip file even on Kodi running on Windows. 

Best regards
Martin

**Comment by wechsler42** [comment]
Dear Heckie,
thanks for your work and sorry for the delay in testing the update.
I have good news from my side:
Kodi Leia 18 Alpha 2 todays built: it just works
Kodi Krypton 17.6: it just works 
Thanks again,
wechsler42
