### ISSUE TITLE
Suggestion: Deutschlandfunk Addon in Kodinerds Repo?

### ISSUE THREAD

**Issue by wechsler42** [Heckie75/kodi-addon-deutschlandfunk#2]
Dear Heckie,
what do you think about offering the DLF plugin within the Kodinerds repo? [Kodinerds](https://www.kodinerds.net)  "Kodinerds.net - Deutschsprachiges Forum zum Kodi Entertainment Center",  offer their own [repo](https://github.com/kodinerds/repo) which is also part of the default repos in LibreELEC.
Thanks,
wechsler42

**Comment by wechsler42** [comment]
Dear Heckie75,
after successfully testing the recent updates of the DLF plugin I would like to get back to the suggestion to offer the plugin in the Kodinerds repo. I really think that this addon would be a very welcome addition.
Thanks,
wechsler42

**Comment by Heckie75** [comment]
Dear Wechsel42,

I have uploaded it here: https://www.kodinerds.net/filebase/index.php/File/14-Sender-Podcasts-des-Deutschlandfunks/

Actually I have no idea if this is correct or not. Maybe you want to double-check it.

Best regards

**Comment by wechsler42** [comment]
Dear Heckie75,
thanks for your effort. I just went to the filebase section of the forum. Perhaps the Addon Development section of the forum might be a place more suitable: [https://www.kodinerds.net/index.php/Board/76-Addon-Development/](https://www.kodinerds.net/index.php/Board/76-Addon-Development/) . There it seems that the addon devs meet rather frequently.
Best,
wechlser42
